# Autogenerated wrapper script for mtdev_jll for aarch64-linux-musl
export libmtdev

JLLWrappers.@generate_wrapper_header("mtdev")
JLLWrappers.@declare_library_product(libmtdev, "libmtdev.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmtdev,
        "lib/libmtdev.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
