# Autogenerated wrapper script for Xorg_xkeyboard_config_jll for any
using Xorg_xkbcomp_jll
JLLWrappers.@generate_wrapper_header("Xorg_xkeyboard_config")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_xkbcomp_jll)
    JLLWrappers.@generate_init_footer()
    if Sys.islinux() || Sys.isfreebsd()
    ENV["XKB_CONFIG_ROOT"] = get(ENV, "XKB_CONFIG_ROOT", joinpath(artifact_dir, "share", "X11", "xkb"))
end

end  # __init__()
