# Autogenerated wrapper script for eudev_jll for armv7l-linux-gnueabihf
export libudev, udevadm, udevd

using gperf_jll
JLLWrappers.@generate_wrapper_header("eudev")
JLLWrappers.@declare_library_product(libudev, "libudev.so.1")
JLLWrappers.@declare_executable_product(udevadm)
JLLWrappers.@declare_executable_product(udevd)
function __init__()
    JLLWrappers.@generate_init_header(gperf_jll)
    JLLWrappers.@init_library_product(
        libudev,
        "lib/libudev.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        udevadm,
        "bin/udevadm",
    )

    JLLWrappers.@init_executable_product(
        udevd,
        "sbin/udevd",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
