# Autogenerated wrapper script for EpollShim_jll for x86_64-unknown-freebsd
export libepoll_shim

JLLWrappers.@generate_wrapper_header("EpollShim")
JLLWrappers.@declare_library_product(libepoll_shim, "libepoll-shim.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepoll_shim,
        "lib/libepoll-shim.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
