QT.gui_private.VERSION = 6.5.3
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/6.5.3 $$QT_MODULE_INCLUDE_BASE/QtGui/6.5.3/QtGui
QT.gui_private.frameworks = 
QT.gui_private.depends = core_private gui
QT.gui_private.uses = xkbcommon
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = evdev freetype system-freetype fontconfig harfbuzz libinput libinput-axis-api linuxfb vnc mtdev vkgen vkkhrdisplay egl_x11 eglfs eglfs_x11 gif ico jpeg png imageio-text-loading tuiotouch xcb-glx xcb-egl-plugin xcb-xlib xcb-sm xkbcommon xkbcommon-x11 xlib multiprocess raster-64bit raster-fp
QT.gui_private.disabled_features = accessibility-atspi-bridge directfb directwrite directwrite3 direct2d direct2d1_1 system-harfbuzz qqnx_imf integrityfb kms drm_atomic integrityhid libinput-hires-wheel-support vsp2 eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_vsp2 eglfs_mali eglfs_viv eglfs_rcar eglfs_viv_wl eglfs_openwfd system-jpeg system-png tslib xcb-native-painting xrender system-xcb-xinput
QMAKE_LIBS_EGL = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lEGL
QMAKE_INCDIR_FREETYPE = /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/freetype2
QMAKE_LIBS_FREETYPE = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lfreetype
QMAKE_LIBS_FONTCONFIG = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lfontconfig
QMAKE_LIBS_LIBINPUT = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -linput
QMAKE_INCDIR_MTDEV = /workspace/destdir/include
QMAKE_LIBS_MTDEV = -L"/workspace/destdir/lib" -lmtdev
QMAKE_LIBS_OPENGL = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lGLX -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lOpenGL
QMAKE_LIBS_OPENGL_ES2 = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lGLESv2
QMAKE_LIBS_VULKAN = 
QMAKE_LIBS_WAYLAND_SERVER = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lwayland-server
QMAKE_LIBS_XLIB = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lX11
QMAKE_LIBS_X11SM = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lICE -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lSM
QMAKE_LIBS_XCB = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb
QMAKE_LIBS_XCB_CURSOR = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-cursor
QMAKE_LIBS_XCB_ICCCM = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-icccm
QMAKE_LIBS_XCB_IMAGE = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-image
QMAKE_LIBS_XCB_KEYSYMS = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-keysyms
QMAKE_LIBS_XCB_RENDERUTIL = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-render-util
QMAKE_LIBS_XCB_RANDR = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-randr
QMAKE_LIBS_XCB_SHAPE = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-shape
QMAKE_LIBS_XCB_SHM = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-shm
QMAKE_LIBS_XCB_SYNC = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-sync
QMAKE_LIBS_XCB_XFIXES = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-xfixes
QMAKE_LIBS_XCB_XLIB = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lX11-xcb
QMAKE_LIBS_XCB_XKB = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-xkb
QMAKE_LIBS_XCB_RENDER = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-render
QMAKE_LIBS_XCB_GLX = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-glx
QMAKE_LIBS_XCB_XINPUT = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxcb-xinput
QMAKE_LIBS_XKBCOMMON = -L"/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib" -lxkbcommon
QMAKE_INCDIR_XKBCOMMON_X11 = /workspace/destdir/include
QMAKE_LIBS_XKBCOMMON_X11 = -L"/workspace/destdir/lib" -lxkbcommon -L"/workspace/destdir/lib" -lxkbcommon-x11
QMAKE_INCDIR_XRENDER = /workspace/destdir/include
QMAKE_LIBS_XRENDER = -L"/workspace/destdir/lib" -lX11 -L"/workspace/destdir/lib" -lXrender
