# Autogenerated wrapper script for Vulkan_Loader_jll for x86_64-w64-mingw32
export libvulkan

JLLWrappers.@generate_wrapper_header("Vulkan_Loader")
JLLWrappers.@declare_library_product(libvulkan, "vulkan-1.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libvulkan,
        "bin\\vulkan-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
