# Autogenerated wrapper script for gperf_jll for x86_64-apple-darwin
export gperf

JLLWrappers.@generate_wrapper_header("gperf")
JLLWrappers.@declare_executable_product(gperf)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gperf,
        "bin/gperf",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
