# Autogenerated wrapper script for Xorg_xcb_util_jll for x86_64-linux-gnu
export libxcb_util

using Xorg_libxcb_jll
JLLWrappers.@generate_wrapper_header("Xorg_xcb_util")
JLLWrappers.@declare_library_product(libxcb_util, "libxcb-util.so.1")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libxcb_jll)
    JLLWrappers.@init_library_product(
        libxcb_util,
        "lib/libxcb-util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
