[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "e6b9fb44029423f5cd69e0cbbff25abcc4b32a8f"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "53d31fd7ac68cf67cfe3f7b98301b35769bfcd443fca7dc02a60f6f869bdb3d1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.aarch64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "062b5a83697ea746e13737b23f8aab14737b1226"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "35825d76db5f96b15a0d747a1f9e51d161415e28138f8d28f3390d5d21bf9305"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "c6e734fde94ab7c91f35987164d69b519c992333"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "95c4ce466883bf72d3cd14172bfc1526e1f8903cea1c07f707537ae49b7ca5dc"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "61d2d048b1b01ead441a41ca0d80fa2ca6496910"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "d297e69c14ed23dc898f64bb9d0cc01f289c26ea8b485f86d97305dba1f6a21a"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.armv6l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2297edd5059b2bc4cca496722c0ccce9ad23e366"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "8cf38bbb90782dac1a5f0900283051d96d84ea24b6723f1466c1a1f01bd65b24"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.armv6l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44e3a6ca151cdd2e1228e1991a24331f329b8a1f"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "075e57e3ce89d98610c6bca12670c2a55561741e08c9fa01a11b73b0a8a5b1bf"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.armv7l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebac696ab3f15dd96510dcf52119d166f6ad45ab"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "ebca1a718468640c7590861bcb8986119b069c048fc524b24c415893a9e11efb"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.armv7l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "a4d5fd9bf7a958cf0008f0b2a4078549337859ef"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "cfb1298a02a7dd059e449f72ada3c7d02c06ca5abbf874b28a1492d39b856f37"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "8e234ee1ca3c1323c8fe07c0c85cb4a288911dcc"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0e08b8c7be848ad090dcd9a9e2fe0e21fb48ea9769010fd56a632b2f320038a9"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "c22853f934c1d060e4ed6cf23b5df6196ce75b28"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "b2918c1cf3946b5858c169b8244b8131fddbcc225ffe9476fb5550032e83b106"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "69eb396a443e175982a3abcdb7c6e2880341c8b2"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "d2496b5425b540af8aa98c62bb1b6dd461d71e7e5ebab695ac6271172fd1732b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2cb0d96a63120d1a0868c905452895a59add9a0d"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "23e979eac7e3b7bf88a231119f8c1d06ded17ea5c41a5dd108f84f27f96c52e1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "387d89822da323c098aba6f8ab316874d4e90f2e"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "e11e34977807b958fe5e7cea59a8354d94e11a052bad1348768aba8143769ea1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "d3f6216e7ff5ce63217c34664b70638ca90a33bf"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "dfb29124b792b7d7919a56c3b55f730ff3ef714f99b519a66579e8e174468ed7"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "db3b0a3ab3d340816110847384a77a9a27c63b9c"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "e2a506e678d77ad2b60bc3764bb54c0c6c0527a1f0859169079b93216c6564d8"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-unknown-freebsd.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "c916a560fa109a4db3d6938a8ab1a6a8b4a09731"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "0a7b3bfbc8b3c3d065597c80c20e9fefc1255477dc8057ffa2702a4dd5f1b966"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-w64-mingw32.tar.gz"
