[[Expat]]
arch = "aarch64"
git-tree-sha1 = "4ec62d729213a748d2300dd0832ebe8ed2292093"
os = "macos"

    [[Expat.download]]
    sha256 = "cbf3634506a0afe598015c545ec371a57dd8c23d2d5a50b8ce58e5fb9ed9d0be"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "f1940aedd9554aaf6ffc9c0aab9bded9d8349014"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "5f8e6dd0667321873d007bdf0ff241cfd7acb6f1ac66ba4438749d2bc03408d1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "b087e0463be7831aadaeaed571e208c0c4fc5fa4"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "a3087184732ce50d1f563824fe42c19b5c8218c903670e94e9b8df976365450e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b68f584fa6919f2ebe1db4cd340885b89f8152f3"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "3e513658ba76ebc9219c585aeb53bc4ddf66e77077c83fcd9e36f0a1d475b486"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5d8e3c1c026c02d2f174fbfa80a94c2e3ff66ae"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "4d1fce720f84e40cc39ad2293082a3a2970574e2ea859a41404ca56871ed472a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "187ca8673ba0f1796350a5a449a60bd03937b915"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1db3c67488b8f2df621085aaff14499c06ee7fe150e4fb99a29963114d8a8c92"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acf558417331353dc21880d7750e7909a00ec811"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "f7f36ed2b87d8a89541afad105bb98c70c6d1a6fb15b4d63ebaaeed86aa20537"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "f68a5bf4673dbd56ca2ec80ff00a81d436f58825"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "86a006eeef52574ddacaf2bbd35e48443ccd48ca2a18db255a158e5fec03408c"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "829311715d377732a5a535a664bdb939a92a8c6c"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "eb509999be88a5eb0739e4217afceeba8a42379d2c334310768ed07ed9ea4214"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "b2adff0feef07ffb1700d8a1e09c78b889d9b991"
os = "windows"

    [[Expat.download]]
    sha256 = "2852a9a30a27d55fcd63f159a8b582269c97bf3811ee6db337bcd6f1ece8697b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "1f547b6daf09863ea0e249e3b3861901ebd779c3"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "91f0df0bc346a87a746bf00b7f64cb578def95d2db135f50e15e97bd24859e13"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "4bebc91892ecb81a8854e8b28747c03f9ee97628"
os = "macos"

    [[Expat.download]]
    sha256 = "13a9f9648bfeccc91f34900a0786cc9c0a8aa427dc3507a41c616d6528d39087"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "2bce74229f51de64c33433272240af5734619b33"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "d9f5baf2dbdb677f0b119ba697c60063fb6549a2bb032b4b8b32665195afa3b9"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "b2683a514defb825998952c1e2bda7e5f1f782bd"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "224eb9236d78c9527c70254a5d19f4d483474e3f7de93dffea9c6ff3babe03f2"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "6c771cc83896343f3932b7218648e179efc74575"
os = "freebsd"

    [[Expat.download]]
    sha256 = "a6ee317f1283706e8815e80fa2dca493a26c077f0df0275a50ef57d8fd4ecaf0"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "dafc9a0c7041340143802ddda690559e5e012daa"
os = "windows"

    [[Expat.download]]
    sha256 = "cbca3e5f7d25e0ef604d3e027bed4565b7a347f686e200df66c07c3c3f163c21"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.5.0+0/Expat.v2.5.0.x86_64-w64-mingw32.tar.gz"
