# Autogenerated wrapper script for Xorg_xcb_util_renderutil_jll for x86_64-unknown-freebsd
export libxcb_render_util

using Xorg_xcb_util_jll
JLLWrappers.@generate_wrapper_header("Xorg_xcb_util_renderutil")
JLLWrappers.@declare_library_product(libxcb_render_util, "libxcb-render-util.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_xcb_util_jll)
    JLLWrappers.@init_library_product(
        libxcb_render_util,
        "lib/libxcb-render-util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
