[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "a3c9c4dbb5af0793ff9b3bd9cda2e1501a29ab9d"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "535dca292fbee71e744055b195fa500196926595e747130e5932ebf56c5c5adc"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "d8a860255e76281c90a877510d892bf300a4c051"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "dee1b2130b5a3126de57c1f56a36f7301ae9ec524201ce9f88bcc7dc36cc8fa7"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82652b62670702f66cd0e35ccc50bcef4c2bb901"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "e1fb8f4e9ab512c945c5760a419b77627efcba2307eb7f6e0e0bbbca50ab5ef2"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f8cccd7ed70063e6b4a9e8529eb6f8f69fa61ee"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "695d152c388bd9814f4be011ba62629eec67c8c0c069b14e67f4b968834b7f61"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62ec7ae6b613fb1ce96be905649c40b7d5e45b12"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "8175cbb4dd615f1e66c911586d3ebf54e9a37fe574b117f29ee49057afe756db"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41e7f85758f9237cbfc4844978b2cd617d2bf35f"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "00add446355a9ed7d467aca684ee5183026bda01c91081978886266d4db397f9"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "1e595b165c5b9e0c32d187810bd37c8eae869ff5"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "3ba1065f3a6d0b91dc3e644367f02043c2f966d86a5329008dd26ec02876c198"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "0113e37e29c27ee03eedc3f3900e375968ac6c57"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "bc7b174b6576d4d32c786cd507032d148e13e6a636dc2026dee6c90ee4bdf91a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "b1674a44b41a6199ecbe663444ff51f176b9e319"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "022f31ba1619bfa5fff4e332e75c617a5cf4ffea0c378d94552ed5b76ef945d9"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "a2422057ec21f1a81d5235915c6657176c30c26b"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "f030656bf8ca3c5afa174cc31772ce7d1832bcec8f9dc68206845a28c38b62a2"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "728ce169c0c8640f2260f6b7d8c27d498c14816c"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "624facd0885fe682e9721e3ed9197cb90f90c449a4d94bd157c0485fb623dc8f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.39.3+0/Libmount.v2.39.3.x86_64-linux-musl.tar.gz"
