[Xorg_xkeyboard_config]
git-tree-sha1 = "f8b49c7c45b400e3f5c4002d19645d4b88712c0c"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "44967eed2c0f1966c5e0e8f34b952793b5d53b5785c9d6c89cbfb6315cb2b847"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.39.0+0/Xorg_xkeyboard_config.v2.39.0.any.tar.gz"
